### ISSUE TITLE
Outdated extension

### ISSUE THREAD

**Issue by studiorockgames** [YoYoGames/GMEXT-GooglePlayBilling#12]
For some time now I have been experiencing problems sending updates to the playstore due to the extension being out of date, other users have received the same error:

"Android 14 has introduced new security changes which affect apps targeting Android 14. In order to ensure compatibility, Google has released Play Billing Library versions 6.0.1 and 5.2.1. When updating your app to target Android 14, following these migration steps, you will need to update your app to either of these versions of the Play Billing Library to be compatible with the recent security changes.

These changes only affect your app when it starts targeting Android 14. Users running Android 14 while your app is not targeting Android 14 are unaffected."

This error is because the extension is not compatible with SDK 34, as it is not updated to version 5.2.1, it seems that the latest version available in the extension is 5.0.0.

The way I have overcome this error is by downgrading from SDK 34 to SDK 33, and it works fine, but recently I am seeing a message when configuring the Android app:

""From August 31 2024 Google Play Billing will require API level of 34+ for new apps or app updates"

It's worrying for me to think that in the near future I will have to stop releasing updates or remove products from my app, I'm looking for another way to overcome this problem.

**Comment by jzavala-YYG** [comment]
Extensions updated and sent to marketplaces. Version 6.1.0
