### ISSUE TITLE
Google Play Billing Library 7.0.0 Release (2024-05-14)

### ISSUE THREAD

**Issue by rochagames** [YoYoGames/GMEXT-GooglePlayBilling#15]
Hello, I recently asked you to update the Google Play billing library to version 6.2.1 and now I'm bothering you again. sorry :grimacing: 

The Google Play Billing Library has updated to version 7.0.0 (2024-05-14) and asks us to update the in-game library to publish or update apps:

"Action required: Migrate to the supported version of the Google Play Library Billing - May 28, 2024 2:01 pm

We are changing the lifecycle of this API and associated deprecation timelines. As you use an older version of the library, check the new important dates to stay compliant:

Until August 31, 2024, all new apps and updates will need to use Billing Library version 6 or later. If you need more time to update your app, you can request an extension until November 1, 2024.

Learn more about the discontinuation at this link.

Update before these deadlines to avoid interrupting app publishing and updates. From the dates mentioned above, it will not be allowed to publish and update apps on the Play Console that use a version of the Play Billing Library prior to 6.

Next steps: Check out more information about how to migrate to the latest version of the Play Billing Library on the developer website."

Message translated from Portuguese by Google Translate, there may be some translation errors.

**Comment by jzavala-YYG** [comment]
Hi @rochagames.

Can you send us the original message with an screenshoot or point us to an official URL?

I found this: https://developer.android.com/google/play/billing/deprecation-faq 
Seems that we have until Aug-31-2026.

Regards

**Comment by rochagames** [comment]
Hello,
Of course, I will send a print of the message received on the Play Console, the only problem is that it is in Portuguese (I'm Brazilian), even if I select the language preferences for English it remains in Portuguese.
The original message:

"Ação necessária: migre para a versão compatível da Biblioteca Google Play Faturamento


May 28, 2024 14:01
Estamos mudando o ciclo de vida dessa API e os cronogramas de descontinuação associados. Como você usa uma versão mais antiga da biblioteca, confira as novas datas importantes para ficar em conformidade:

Até 31 de agosto de 2024, todos os novos apps e atualizações precisarão usar a versão 6 ou mais recente da Biblioteca Faturamento. Se você precisar de mais tempo para atualizar seu app, é possível pedir uma extensão até 1º de novembro de 2024.

Saiba mais sobre a descontinuação [neste link](https://notifications.google.com/g/p/ANiao5qJCE-72F-O717Q9-Po7yoTOFGHR6_gYx5Eq3Wq4Yl0L_K-4m9zv7Xphyjn6HGQCYK9XHk6OSBYefXBWGSCO2xGql5SjRvl0AC_pxFae0ib4KpvzYAItH1mAZC0R7Ykdy-bXosmKXNh2_QRPhnJtC2x6KijBBEiJn-5BbvcZSZ50QK8mvQkxpIOULN8ZQLd-4BRqMte2KvzjGg8k3AmMGg71GG6tzDpT7Yc0MM3s3VGA01PYiVmU2hsRMyvWKQCQkKAPOF6).

Atualize antes desses prazos para não interromper a publicação e as atualizações de apps. A partir das datas mencionadas acima, não vai ser permitido publicar e atualizar apps no Play Console que usam uma versão da Biblioteca Play Faturamento anterior à 6.

Próximas etapas: confira mais informações sobre como migrar para a versão mais recente da Biblioteca Play Faturamento no [site do desenvolvedor](https://notifications.google.com/g/p/ANiao5qohJRooQj1liFi-u8uCndyTURQhO5EObCC5J_JybZTp5xru0CpZY7Nogwd6fgRxymg9GymUPHLi4_NxNFeDQnld7e8convy6jzFDF4lL1LN9gmBQKtpTV_3ridFoOA_xlgOuO-Qo4YUcO2TvESlK1COGzfyFcWLSaTj2PZW8hYy8JfhAgpTCmwTVaeNEFl3mE2BbENKeFTmf9LoPVKZgAxtJhDpi6o8ua5skky9TzAlfoWEq-iBh6vhiR0A6XOdmjVqFfw2OUQYZPpR82WrVQZ)."

Note: I didn't receive anything in the email.

![screenshot_2](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/166463194/58d95b34-09b3-4f41-93fb-c62d6ff733ce)
![screenshot_1](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/166463194/b2ad6a20-0ac0-4a0c-a145-6abc483aed31)

**Comment by jzavala-YYG** [comment]
If I'm correct the message does reference to the version 6, you only have to update to our last version to be safe until 2026.

**Comment by rochagames** [comment]
> If I'm correct the message does reference to the version 6, you only have to update to our last version to be safe until 2026.

The message actually says that there will be support for version 6 or higher.
I believed I had the latest version but it must be out of date (or maybe it's just a Google alert message), I'm really sorry for creating the issue!
