### ISSUE TITLE
How to check that a subscription is active or cancelled?

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-GooglePlayBilling#16]
Hello,

I hope this kind of question is allowed here, but I can't seem to understand the logic of how to confirm a valid subscription.
I want to simply check and confirm that the subscription is either active or cancelled. I would then act accordingly.

Thanks for the help

**Comment by jzavala-YYG** [comment]
Hello @Callsign54 

Take a look to to the project attached in the extension.

Put special attention to extension function **_GPBilling_QueryPurchasesAsync()_** the async event **_gpb_purchase_skutype_inapp_** and the project function **_updatePurchasesData()_**

Additional you can you can use see the **_SERVER VERIFICATION_** example attached in the **_Obj_GooglePlayBilling_**.

Regards
