### ISSUE TITLE
Redeeming Free IAP Key Causes Crash

### ISSUE THREAD

**Issue by npapalia** [YoYoGames/GMEXT-GooglePlayBilling#17]
Hey there, I wanted to quickly ask about a problem we've encountered and are having a hard time solving. Everything related to our in-app-purchases on Android work, but code redemption for a free copy of an IAP isn't being recognized, and causes a hard crash in our current code. We are guessing that this needs to be handled in a different way than usual purchases, but cannot find the documentation/resources to see where to do that. Could you point us towards how to handle this?

This happens when the player who has redeemed the IAP (non-repeatable, one time purchase) encounters the check to ensure that players have purchased this IAP in the game.

![IMG_0386](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/88669535/3b6cc221-6644-444d-93a3-311d5f73a28b)
![image](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/88669535/34f0ad83-4070-40c2-8448-940383c084f9)

**Comment by jzavala-YYG** [comment]
Hello @npapalia, can you send us the string of **__json_**.
Probably it's not presented acknowledged but you can handle it as acknowledged=false if acknowledged doesn't exists

**Comment by patrickrocheyoyo** [comment]
Closing and awaiting feedback.
