### ISSUE TITLE
The extension isn't accepted by google play

### ISSUE THREAD

**Issue by Markieboyyy** [YoYoGames/GMEXT-GooglePlayBilling#19]
In the picture you see "implementation 'com.android.billingclient:billing:6.1.0" but it needs to be 7.0.0 or higher because google play doesn't accept it anymore... How can I fix this, because the extension of yoyo games on the marketplace (amd github) is still with the 6.1.0 library...
![image](https://github.com/user-attachments/assets/92dd2523-9741-47c5-a291-583d01467dd8)

**Comment by Schwarzgamescom** [comment]
Library 6.1.0 works, Google accepts 6.0.1 and above. Yesterday I updated 3 apps with library 6.1.0 and the same day they were all accepted. I also got notifications, that all remaining issues are resolved.

**Comment by Markieboyyy** [comment]
> Library 6.1.0 works, Google accepts 6.0.1 and above. Yesterday I updated 3 apps with library 6.1.0 and the same day they were all accepted. I also got notifications, that all remaining issues are resolved.

![image](https://github.com/user-attachments/assets/b5117221-bb57-4be5-9142-f35fbb29f084)

**Comment by Markieboyyy** [comment]
they are talking about upgrading to a higer version of google play billing

**Comment by Schwarzgamescom** [comment]
Yes, they are talking about upgrading to v6 or higher, therefore v6.1.0 is good.

**Comment by Markieboyyy** [comment]
> Yes, they are talking about upgrading to v6 or higher, therefore v6.1.0 is good.

Oh oke, so do i have to do something now or not because the error doesn't go away...

**Comment by jzavala-YYG** [comment]
Hello @Markieboyyy  
Update your extension, clean your cache, build and try update your games on play store.
You should be ok with the current version.

**Comment by Swensson** [comment]
Hi,
I have used the version before this one but also need to update now. Have gone through the versions in game maker but can't find any differences. Is it true that I only need to replace "GooglePlayBillingExtension" to version 1.1.0 and nothing else?
