### ISSUE TITLE
Error receiving broadcast Intent { act=com.android.vending.billing.LOCAL_BROADCAST_PURCHASES_UPDATED

### ISSUE THREAD

**Issue by TaylorDale** [YoYoGames/GMEXT-GooglePlayBilling#20]
Following error occurs at GooglePlayBillingService.java:80 : 

Caused by java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

Extension version 1.1.0 with implementation 'com.android.billingclient:billing:6.2.1'
In a production build with real users, across 2 devices with 2 different android versions.

See below:
<img width="977" alt="image" src="https://github.com/user-attachments/assets/fc27fe0e-4c8a-4e1d-befd-017e44282b5d">

Using:
classpath 'com.android.tools.build:gradle:8.5.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip

to compile.

**Comment by jzavala-YYG** [comment]
I updated the extensions to 6.2.1 and added condition for when purchases are null. please re-open this ticket if problems persists.
