### ISSUE TITLE
Contributing to the documentation

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-GooglePlayBilling#3]
Is it possible to open source the source text for the included file PDF or provide a Google Doc link where contributors can suggest editions?

**Comment by DiasFranciscoA** [comment]
Hello @shichen85, we are corrently on the process of moving documentation to the Github wiki. As we are doing with all the other extensions meanwhile I'll try to check whether or not that (Google Doc link) would be possible to provide.

**Comment by shichen85** [comment]
> Hello @shichen85, we are corrently on the process of moving documentation to the Github wiki. As we are doing with all the other extensions meanwhile I'll try to check whether or not that (Google Doc link) would be possible to provide.

Thanks for looking into this!

**Comment by DiasFranciscoA** [comment]
The documenation is now completly ported to wiki docs and you are free to contribute to it.
This issue will now be closed.
