### ISSUE TITLE
[DOCUMENTATION] Mismatched variables names in the wiki pages

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GMEXT-GooglePlayBilling#5]
I've noticed that some of the variables on this wiki page are getting json data  under one variable name, but used a different name for parsing from json. 
(Side note, mostly making an issue over a PR as I'm actually very unfamiliar with making contributions to wiki pages)
https://github.com/YoYoGames/GMEXT-GooglePlayBilling/wiki/Quick_Start_Guide#querying-purchases
<img width="286" alt="chrome_2023-09-03_20-53-11" src="https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/26135221/5957da54-e829-418b-acf4-8d74ef689cae">

**Comment by DiasFranciscoA** [comment]
Thank you for pointing out the typo. We are progressively transitioning to a new documentation format which will enable users to contribute directly to the documentation via a standard GitHub PR to the main branch. Currently, this feature is available in some of our extension repositories, but not all have been updated to this format yet.

We will be addressing the issues manually for now. Most of them will be also fixed when the technical write team goes through the extension documentation during the conversion process.

**Comment by tabularelf** [comment]
All good! Also, there was *more* than one I did mention. This wasn't still changed 😅 
![image](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/assets/26135221/6e676936-8680-4871-8005-2699b477d592)

**Comment by YYBartT** [comment]
The second typo is now also fixed
