### ISSUE TITLE
[DOCUMENTATION] [DEMO IMPROVEMENTS] Out of date documentation on Gamemaker Help Center

### ISSUE THREAD

**Issue by j4m1ef0rd** [YoYoGames/GMEXT-GooglePlayBilling#7]
The guide on [here](https://help.yoyogames.com/hc/en-us/articles/360031457831-Android-Using-The-Google-Play-IAP-Extension) is still using the `GPBilling_QueryPurchases` function that no longer exists.
This is the only real tutorial for implementing and android IAP, so it should be kept up-to-date. Also it doesn't help that the sample code that comes with the extension is very difficult to follow with its use of inherited events, parents objects and methods declared in the create event instead of using scripts.

**Comment by DiasFranciscoA** [comment]
In the future, we plan to phase out the help center to consolidate all information in one location, preventing discrepancies arising from outdated documents. As for the methods, you can middle-click on them, and they should open in a new window. We appreciate your feedback and will consider it when enhancing the demo project.

**Comment by YYBartT** [comment]
The article's contents have been moved to the [wiki page](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/wiki/Using_The_Google_Play_IAP_Extension) and the article in the Help Center now shows a warning message linking to this new wiki page. The code examples that were in the article are no longer there but can be found on the other guide page: [Quick Start Guide](https://github.com/YoYoGames/GMEXT-GooglePlayBilling/wiki/Quick_Start_Guide).
